name: CI

on:
  pull_request:
    branches: [master]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint "src/**/*.{js,jsx,ts,tsx}"

      - name: Run Prettier check
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,css,scss,json,md}"

      - name: Build project
        run: npm run build
